### ISSUE TITLE
Can't open trajectory on Windows

### ISSUE THREAD

**Issue by ab5424** [Molara-Lab/Molara#353]
On Windows, I can't open the `examples/xyz/opt.xyz` file. I can import it but when I click on the second image o the trajectory, the following error appears:

```
dict_keys([<class 'bytes'>, <class 'OpenGL.converters.c_long_Array_1'>, <class 'numpy.ndarray'>, <class 'pyrr.objects.vector3.Vector3'>, <class 'ctypes.c_void_p'>, <class 'NoneType'>])
Traceback (most recent call last):
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHub\Molara\src\molara\Gui\trajectory_dialog.py", line 103, in get_next_mol
    self.update_molecule()
  File "D:\GitHub\Molara\src\molara\Gui\trajectory_dialog.py", line 134, in update_molecule
    self.parent().structure_widget.set_structure(
  File "D:\GitHub\Molara\src\molara\Gui\structure_widget.py", line 146, in set_structure
    self.set_vertex_attribute_objects()
  File "D:\GitHub\Molara\src\molara\Gui\structure_widget.py", line 196, in set_vertex_attribute_objects
    self.renderer.update_atoms_vao(
  File "D:\GitHub\Molara\src\molara\Rendering\rendering.py", line 295, in update_atoms_vao
    glDeleteBuffers(1, buffer)
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\latebind.py", line 47, in __call__
    return self._finalCall( *args, **named )
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\wrapper.py", line 689, in wrapperCall
    pyArgs = tuple( calculate_pyArgs( args ))
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\wrapper.py", line 450, in calculate_pyArgs
    yield converter(args[index], self, args)
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\converters.py", line 135, in __call__
    return self.function( incoming )
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\arrays\arraydatatype.py", line 171, in asArray
    return cls.getHandler(value).asArray(value, typeCode or cls.typeConstant)
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\arrays\arraydatatype.py", line 59, in __call__
    raise TypeError(
TypeError: ('No array-type handler for type numpy.uintc (value: 2) registered', <OpenGL.converters.CallFuncPyConverter object at 0x00000254AD2D9F90>)
dict_keys([<class 'bytes'>, <class 'OpenGL.converters.c_long_Array_1'>, <class 'numpy.ndarray'>, <class 'pyrr.objects.vector3.Vector3'>, <class 'ctypes.c_void_p'>, <class 'NoneType'>])
dict_keys([<class 'bytes'>, <class 'OpenGL.converters.c_long_Array_1'>, <class 'numpy.ndarray'>, <class 'pyrr.objects.vector3.Vector3'>, <class 'ctypes.c_void_p'>, <class 'NoneType'>])
Traceback (most recent call last):
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\wrapper.py", line 689, in wrapperCall
    pyArgs = tuple( calculate_pyArgs( args ))
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\wrapper.py", line 450, in calculate_pyArgs
    yield converter(args[index], self, args)
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\converters.py", line 135, in __call__
    return self.function( incoming )
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\arrays\arraydatatype.py", line 171, in asArray
    return cls.getHandler(value).asArray(value, typeCode or cls.typeConstant)
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\arrays\arraydatatype.py", line 59, in __call__
    raise TypeError(
TypeError: ('No array-type handler for type numpy.uintc (value: 2) registered', <OpenGL.converters.CallFuncPyConverter object at 0x00000254AD2D9F90>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHub\Molara\src\molara\Gui\trajectory_dialog.py", line 103, in get_next_mol
    self.update_molecule()
  File "D:\GitHub\Molara\src\molara\Gui\trajectory_dialog.py", line 134, in update_molecule
    self.parent().structure_widget.set_structure(
  File "D:\GitHub\Molara\src\molara\Gui\structure_widget.py", line 146, in set_structure
    self.set_vertex_attribute_objects()
  File "D:\GitHub\Molara\src\molara\Gui\structure_widget.py", line 196, in set_vertex_attribute_objects
    self.renderer.update_atoms_vao(
  File "D:\GitHub\Molara\src\molara\Rendering\rendering.py", line 295, in update_atoms_vao
    glDeleteBuffers(1, buffer)
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\latebind.py", line 47, in __call__
    return self._finalCall( *args, **named )
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\wrapper.py", line 689, in wrapperCall
    pyArgs = tuple( calculate_pyArgs( args ))
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\wrapper.py", line 450, in calculate_pyArgs
    yield converter(args[index], self, args)
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\converters.py", line 135, in __call__
    return self.function( incoming )
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\arrays\arraydatatype.py", line 171, in asArray
    return cls.getHandler(value).asArray(value, typeCode or cls.typeConstant)
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\arrays\arraydatatype.py", line 59, in __call__
    raise TypeError(
TypeError: ('No array-type handler for type numpy.uintc (value: 2) registered', <OpenGL.converters.CallFuncPyConverter object at 0x00000254AD2D9F90>)
```

**Comment by ab5424** [comment]
On Mac, it runs just fine.

**Comment by Michel-Heinz** [comment]
looks like some opengl problem upon deleting a buffer. I ll have to debug on a windows machine.
