### ISSUE TITLE
Error after fresh install: numpy 2.0.0 not supported (apparently)

### ISSUE THREAD

**Issue by adrianusler** [Molara-Lab/Molara#426]
Error when calling `molara` after a fresh install. I have already tried updating my numpy version outside of the venv to 2.0.0 and re-installing, but that didn't help. Perhaps we need to change the installation such that an older numpy version is installed until we have figured out how to deal with the new numpy version?
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<...>/Molara/venv/bin/molara", line 7, in <module>
    from molara.__main__ import main
  File "<...>/Molara/src/molara/__main__.py", line 15, in <module>
    from molara.Gui.main_window import MainWindow
  File "<...>/Molara/src/molara/Gui/main_window.py", line 12, in <module>
    from molara.Gui.builder import BuilderDialog
  File "<...>/Molara/src/molara/Gui/builder.py", line 14, in <module>
    from molara.Structure.molecule import Molecule
  File "<...>/Molara/src/molara/Structure/molecule.py", line 10, in <module>
    from molara.Structure.structure import Structure
  File "<...>/Molara/src/molara/Structure/structure.py", line 12, in <module>
    from molara.Structure.drawer import Drawer
  File "<...>/Molara/src/molara/Structure/drawer.py", line 9, in <module>
    from molara.Rendering.cylinder import Cylinder, calculate_cylinder_model_matrix
Traceback (most recent call last):
  File "<...>/Molara/venv/bin/molara", line 7, in <module>
    from molara.__main__ import main
  File "<...>/Molara/src/molara/__main__.py", line 15, in <module>
    from molara.Gui.main_window import MainWindow
  File "<...>/Molara/src/molara/Gui/main_window.py", line 12, in <module>
    from molara.Gui.builder import BuilderDialog
  File "<...>/Molara/src/molara/Gui/builder.py", line 14, in <module>
    from molara.Structure.molecule import Molecule
  File "<...>/Molara/src/molara/Structure/molecule.py", line 10, in <module>
    from molara.Structure.structure import Structure
  File "<...>/Molara/src/molara/Structure/structure.py", line 12, in <module>
    from molara.Structure.drawer import Drawer
  File "<...>/Molara/src/molara/Structure/drawer.py", line 9, in <module>
    from molara.Rendering.cylinder import Cylinder, calculate_cylinder_model_matrix
  File "src/molara/Rendering/cylinder.pyx", line 1, in init molara.Rendering.cylinder
    """This module contains the Cylinder and Cylinders classes.
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

**Comment by ab5424** [comment]
@adrianusler Fixed by [1baa898](https://github.com/Molara-Lab/Molara/commit/1baa8981171a91bc9ae92c986133d4160a72e3ad).
