### ISSUE TITLE
Cannot install from wheel because of missing `settings` folder

### ISSUE THREAD

**Issue by ab5424** [Molara-Lab/Molara#453]
```
(Molara) alexbonkowski@182-151 Molara % molara examples/xyz/ferrocene.xyz                                      
Traceback (most recent call last):
  File "/Users/alexbonkowski/PycharmProjects/venv/Molara/bin/molara", line 8, in <module>
    sys.exit(main())
  File "/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/site-packages/molara/__main__.py", line 36, in main
    widget = MainWindow()
  File "/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/site-packages/molara/Gui/main_window.py", line 57, in __init__
    self.structure_customizer_dialog = StructureCustomizerDialog(self)
  File "/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/site-packages/molara/Gui/structure_customizer_dialog.py", line 43, in __init__
    self.update_settings_box()
  File "/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/site-packages/molara/Gui/structure_customizer_dialog.py", line 77, in update_settings_box
    for f in listdir(f"{self.src_path}/Settings/Structure")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/Settings/Structure'
```

**Comment by ab5424** [comment]
Once this is fixed we can do a new release.
