### ISSUE TITLE
Rendering error of MOs on Windows

### ISSUE THREAD

**Issue by ab5424** [Molara-Lab/Molara#520]
On Windows, I get the following error when attempting to change the MO that is displayed in the main window:
```
dict_keys([<class 'bytes'>, <class 'OpenGL.converters.c_long_Array_1'>, <class 'numpy.ndarray'>, <class 'ctypes.c_char_Array_84'>, <class 'pyrr.objects.vector3.Vector3'>, <class 'ctypes.c_void_p'>, <class 'int'>, <class 'ctypes.c_ulong'>, <class 'NoneType'>])
dict_keys([<class 'bytes'>, <class 'OpenGL.converters.c_long_Array_1'>, <class 'numpy.ndarray'>, <class 'ctypes.c_char_Array_84'>, <class 'pyrr.objects.vector3.Vector3'>, <class 'ctypes.c_void_p'>, <class 'int'>, <class 'ctypes.c_ulong'>, <class 'NoneType'>])
Traceback (most recent call last):
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\wrapper.py", line 689, in wrapperCall
    pyArgs = tuple( calculate_pyArgs( args ))
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\wrapper.py", line 450, in calculate_pyArgs
    yield converter(args[index], self, args)
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\converters.py", line 135, in __call__
    return self.function( incoming )
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\arrays\arraydatatype.py", line 171, in asArray
    return cls.getHandler(value).asArray(value, typeCode or cls.typeConstant)
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\arrays\arraydatatype.py", line 59, in __call__
    raise TypeError(
TypeError: ('No array-type handler for type numpy.uintc (value: np.uint32(10)) registered', <OpenGL.converters.CallFuncPyConverter object at 0x000001949D4AC0A0>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHub\Molara\src\molara\gui\mos_dialog.py", line 229, in closeEvent
    self.remove_orbitals()
  File "D:\GitHub\Molara\src\molara\gui\mos_dialog.py", line 381, in remove_orbitals
    self.parent().structure_widget.renderer.remove_polygon(orb)
  File "D:\GitHub\Molara\src\molara\rendering\rendering.py", line 130, in remove_polygon
    glDeleteBuffers(1, buffer)
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\latebind.py", line 47, in __call__
    return self._finalCall( *args, **named )
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\wrapper.py", line 689, in wrapperCall
    pyArgs = tuple( calculate_pyArgs( args ))
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\wrapper.py", line 450, in calculate_pyArgs
    yield converter(args[index], self, args)
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\converters.py", line 135, in __call__
    return self.function( incoming )
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\arrays\arraydatatype.py", line 171, in asArray
    return cls.getHandler(value).asArray(value, typeCode or cls.typeConstant)
  File "D:\PycharmProjects\Molara-venv\lib\site-packages\OpenGL\arrays\arraydatatype.py", line 59, in __call__
    raise TypeError(
TypeError: ('No array-type handler for type numpy.uintc (value: np.uint32(10)) registered', <OpenGL.converters.CallFuncPyConverter object at 0x000001949D4AC0A0>)
```

**Comment by ab5424** [comment]
I can't replicate this anymore, closing.
